# Generated by Django 3.2 on 2022-08-28 10:48

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderitem',
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_confirmation',
            field=models.BooleanField(default=False, help_text='you must confirmation your order', verbose_name='active'),
        ),
    ]
