# Generated by Django 3.2 on 2022-08-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220828_1048'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderitem',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_confirmation',
        ),
    ]
